#! /usr/bin/env zsh

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# Append history as commands are executed
setopt inc_append_history

# Don't save duplicates
setopt hist_ignore_all_dups

# Disable sharing history between terminals (sessions)
unsetopt share_history

# Expansion and Globbing
# treat #, ~, and ^ as part of patterns for filename generation
setopt extended_glob
